process {
    executor = 'slurm'
    errorStrategy = 'retry'
    maxRetries = 2
}

executor {
    queueSize = 30
}

singularity {
    cacheDir = '/path/to/singularity/containers/'
}

workDir = '/path/to/working/directory/'
