process {
    executor = 'slurm'
    errorStrategy = 'retry'
    maxRetries = 2
}

executor {
    queueSize = 30
}

singularity {
    cacheDir = '/data/bbg/datasets/pipelines/nextflow_containers/'
}

workDir = '/scratch/bbg/work/20260107_pmc_case_sarek/'
